import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, Stethoscope } from "lucide-react";
import { catalogEffectiveDate, diodePackages, formatTreatmentPrice, treatmentCategories, treatments } from "@/lib/services/catalog";

export const metadata: Metadata = { title: "Treatments & Prices", description: "Explore ESCLARE facials, laser treatments, lifting, skin support, wellness, doctor procedures, and regular prices.", alternates: { canonical: "/treatments" } };
const php = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 0 });

export default function TreatmentsPage() {
  return <main><section className="bg-[#32101E] py-16 text-white sm:py-24"><div className="public-container"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#E8D5B5]">Transparent regular rates</p><h1 className="mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-6xl">Treatments designed around your goals.</h1><p className="mt-6 max-w-2xl leading-8 text-[#E7DAD2]">Explore starting information before your visit. Final suitability and treatment plans are confirmed after assessment.</p><p className="mt-5 text-xs text-[#CDBBB0]">Price reference effective {new Date(`${catalogEffectiveDate}T00:00:00`).toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" })}.</p></div></section>
    <nav aria-label="Treatment categories" className="sticky top-[72px] z-30 overflow-x-auto border-b border-[#D8C9B4] bg-[#FBF8F2]/95 backdrop-blur-xl"><div className="public-container flex min-w-max gap-6 py-4">{treatmentCategories.map((category) => <a key={category} href={`#${category.replaceAll(" ", "-").toLowerCase()}`} className="public-link pb-1 text-xs font-bold uppercase tracking-[0.06em] text-[#5B1830]">{category}</a>)}<a href="#4d-diode-packages" className="public-link pb-1 text-xs font-bold uppercase tracking-[0.06em] text-[#5B1830]">4D Diode</a></div></nav>
    <div className="public-container py-16 sm:py-24">{treatmentCategories.map((category, categoryIndex) => { const items = treatments.filter((item) => item.public && item.category === category); return <section key={category} id={category.replaceAll(" ", "-").toLowerCase()} className="scroll-mt-36 border-t border-[#CCBCA7] py-12 first:border-t-0 first:pt-0" aria-labelledby={`heading-${categoryIndex}`}><div className="grid gap-8 lg:grid-cols-[0.32fr_0.68fr]"><div data-reveal><p className="public-eyebrow">0{categoryIndex + 1}</p><h2 id={`heading-${categoryIndex}`} className="mt-3 text-3xl text-[#481827]">{category}</h2><p className="mt-3 text-sm text-[#746A6D]">{items.length} {items.length === 1 ? "treatment" : "treatments"}</p></div><div className="grid gap-px bg-[#D8C9B4] sm:grid-cols-2">{items.map((item) => <article key={item.slug} className="group min-h-60 bg-white p-6 transition-all duration-300 hover:relative hover:z-10 hover:-translate-y-1 hover:shadow-[0_18px_50px_rgba(65,30,42,0.13)]" data-reveal><div className="flex items-start justify-between gap-4"><h3 className="text-xl text-[#3F1724]">{item.name}</h3>{item.doctorRequired && <span className="inline-flex shrink-0 items-center gap-1 bg-[#F2E7E2] px-2 py-1 text-[10px] font-bold uppercase text-[#6F263D]"><Stethoscope size={12} /> Doctor</span>}</div><p className="mt-4 text-sm leading-7 text-[#625D58]">{item.summary}</p><div className="mt-7 border-t border-[#E8E0D7] pt-4"><p className="text-sm font-bold text-[#6F263D]">{formatTreatmentPrice(item)}</p></div></article>)}</div></div></section>; })}
      <section id="4d-diode-packages" className="scroll-mt-36 border-t border-[#CCBCA7] pt-14"><div className="grid gap-8 lg:grid-cols-[0.32fr_0.68fr]"><div data-reveal><p className="public-eyebrow">Package menu</p><h2 className="mt-3 text-3xl text-[#481827]">4D Diode packages</h2><p className="mt-4 text-sm leading-7 text-[#6B6264]">Package totals for 2-6 sessions. The recommended course is commonly at least 8 sessions, with individual results varying.</p><div className="mt-6 flex gap-3 text-sm leading-6 text-[#625D58]"><CheckCircle2 className="mt-0.5 shrink-0 text-[#9A7740]" size={18} /><span>4-wavelength system with cooling support</span></div></div><div className="overflow-x-auto border border-[#D8C9B4] bg-white" data-reveal><table className="w-full min-w-[680px] border-collapse text-left text-sm"><thead className="bg-[#5B1830] text-white"><tr><th className="p-4">Treatment area</th>{[2,3,4,5,6].map((count) => <th className="p-4" key={count}>{count} sessions</th>)}</tr></thead><tbody>{diodePackages.map((item) => <tr key={item.area} className="border-t border-[#E8E0D7] transition-colors hover:bg-[#F6F0E8]"><th className="p-4 font-semibold text-[#481827]">{item.area}<span className="mt-1 block text-[10px] font-normal uppercase text-[#8A7A6F]">{item.category}</span></th>{item.options.map((option) => <td className="p-4" key={option.sessions}>{php.format(option.price)}</td>)}</tr>)}</tbody></table></div></div></section>
    </div><section className="bg-[#EEE6DA] py-14"><div className="public-container flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="public-eyebrow">Personal guidance</p><h2 className="mt-3 text-3xl text-[#481827]">Not sure where to begin?</h2><p className="mt-2 text-sm text-[#62595C]">Tell the team what you would like to improve and request an assessment.</p></div><Link href="/appointment-request" className="luxury-button shrink-0"><CalendarDays size={17} /> Request appointment <ArrowRight size={16} /></Link></div></section></main>;
}
