import { calculateAge, calculateBmi, maskPhilippineMobile } from "./utils";
import type { PatientAuditRecord, PatientProfile } from "./types";

type DemoPatientProfile = PatientProfile & {
  mobile: string;
  email: string | null;
};

const nagaBranch = {
  id: "00000000-0000-4000-8000-000000000101",
  name: "ESCLARE Naga",
};

const daetBranch = {
  id: "00000000-0000-4000-8000-000000000102",
  name: "ESCLARE Daet",
};

export const demoPatients: DemoPatientProfile[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    patientNumber: "ESC-P-0001",
    firstName: "Liana",
    middleName: "Reyes",
    lastName: "Cruz",
    preferredName: "Lia",
    sexAtBirth: "female",
    dateOfBirth: "1994-08-14",
    age: calculateAge("1994-08-14"),
    homeBranchId: nagaBranch.id,
    homeBranchName: nagaBranch.name,
    maskedMobile: maskPhilippineMobile("09171234567"),
    mobile: "09171234567",
    email: "liana.cruz@example.test",
    remainingSessions: 4,
    outstandingBalance: 0,
    loyaltyPoints: 320,
    lastVisitAt: "2026-07-02T10:30:00+08:00",
    nextAppointmentAt: "2026-07-30T11:00:00+08:00",
    clinicalAlertLevel: "caution",
    archivedAt: null,
    address: {
      country: "Philippines",
      region: "Bicol Region",
      province: "Camarines Sur",
      cityMunicipality: "Naga City",
      barangay: "Fictional Barangay",
      street: "Sample Street",
      building: "Unit 2",
      postalCode: "4400",
    },
    emergencyContact: {
      name: "Mara Cruz",
      relationship: "Sister",
      mobile: "09175550101",
      secondaryContact: null,
    },
    physicalInfo: { heightCm: 162, weightKg: 55, bmi: calculateBmi(162, 55) },
    medicalProfile: {
      alertLevel: "caution",
      alertReason: "Reports recent sun exposure.",
      allergies: ["Fragrance sensitivity"],
      currentMedications: ["Vitamin C supplement"],
      medicalConditions: ["Mild eczema history"],
      pregnancyStatus: "no",
      breastfeeding: false,
      keloidHistory: false,
      photosensitivity: true,
      diabetes: false,
      hypertension: false,
      otherClinicalNotes: "Patch test recommended before stronger peels.",
      updatedAt: "2026-07-02T10:30:00+08:00",
    },
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    patientNumber: "ESC-P-0002",
    firstName: "Paolo",
    middleName: null,
    lastName: "Villanueva",
    preferredName: null,
    sexAtBirth: "male",
    dateOfBirth: "1989-03-21",
    age: calculateAge("1989-03-21"),
    homeBranchId: daetBranch.id,
    homeBranchName: daetBranch.name,
    maskedMobile: maskPhilippineMobile("09181234567"),
    mobile: "09181234567",
    email: "paolo.villanueva@example.test",
    remainingSessions: 2,
    outstandingBalance: 1850,
    loyaltyPoints: 140,
    lastVisitAt: "2026-06-28T14:00:00+08:00",
    nextAppointmentAt: null,
    clinicalAlertLevel: "doctor_review_required",
    archivedAt: null,
    address: {
      country: "Philippines",
      region: "Bicol Region",
      province: "Camarines Norte",
      cityMunicipality: "Daet",
      barangay: "Demo Barangay",
      street: "Clinic Road",
      building: null,
      postalCode: "4600",
    },
    emergencyContact: {
      name: "Nico Villanueva",
      relationship: "Brother",
      mobile: "09185550102",
      secondaryContact: "Home line on file",
    },
    physicalInfo: { heightCm: 174, weightKg: 78, bmi: calculateBmi(174, 78) },
    medicalProfile: {
      alertLevel: "doctor_review_required",
      alertReason: "Hypertension noted during intake.",
      allergies: [],
      currentMedications: ["Maintenance medication on file"],
      medicalConditions: ["Hypertension"],
      pregnancyStatus: "not_applicable",
      breastfeeding: null,
      keloidHistory: false,
      photosensitivity: false,
      diabetes: false,
      hypertension: true,
      otherClinicalNotes: "Doctor assessment required before energy-based procedures.",
      updatedAt: "2026-06-28T14:00:00+08:00",
    },
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    patientNumber: "ESC-P-0003",
    firstName: "Camille",
    middleName: "Ong",
    lastName: "Dela Paz",
    preferredName: "Cam",
    sexAtBirth: "female",
    dateOfBirth: "2000-11-09",
    age: calculateAge("2000-11-09"),
    homeBranchId: nagaBranch.id,
    homeBranchName: nagaBranch.name,
    maskedMobile: maskPhilippineMobile("+639191234567"),
    mobile: "+639191234567",
    email: null,
    remainingSessions: 0,
    outstandingBalance: 0,
    loyaltyPoints: 75,
    lastVisitAt: null,
    nextAppointmentAt: "2026-07-15T09:30:00+08:00",
    clinicalAlertLevel: "informational",
    archivedAt: null,
    address: null,
    emergencyContact: null,
    physicalInfo: { heightCm: null, weightKg: null, bmi: null },
    medicalProfile: {
      alertLevel: "informational",
      alertReason: "First visit intake incomplete.",
      allergies: [],
      currentMedications: [],
      medicalConditions: [],
      pregnancyStatus: "unknown",
      breastfeeding: null,
      keloidHistory: null,
      photosensitivity: null,
      diabetes: null,
      hypertension: null,
      otherClinicalNotes: "Complete medical profile before treatment.",
      updatedAt: "2026-07-10T09:00:00+08:00",
    },
  },
];

export const demoPatientAudit: PatientAuditRecord[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    action: "patient.view",
    entityType: "patients",
    reason: "Directory access",
    actorRole: "receptionist",
    branchId: nagaBranch.id,
    createdAt: "2026-07-10T09:10:00+08:00",
    success: true,
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    action: "patient.contact_reveal",
    entityType: "patients",
    reason: "Appointment confirmation",
    actorRole: "receptionist",
    branchId: nagaBranch.id,
    createdAt: "2026-07-10T09:12:00+08:00",
    success: true,
  },
];
