export const PERMISSIONS = [
  "dashboard.owner.view",
  "dashboard.branch.view",
  "patients.view_basic",
  "patients.create",
  "patients.update_basic",
  "patients.archive",
  "patients.reveal_contact",
  "patients.export",
  "medical.view_summary",
  "medical.view_full",
  "medical.create",
  "medical.update",
  "medical.sign",
  "medical.add_addendum",
  "clinical_photos.view",
  "clinical_photos.upload",
  "clinical_photos.download",
  "clinical_photos.view_sensitive",
  "appointments.view",
  "appointments.create",
  "appointments.confirm",
  "appointments.reschedule",
  "appointments.cancel",
  "appointments.check_in",
  "appointments.start_treatment",
  "appointments.complete",
  "services.view",
  "services.create",
  "services.update",
  "services.archive",
  "prices.view",
  "prices.propose",
  "prices.approve",
  "prices.publish",
  "payments.create",
  "payments.view",
  "payments.refund_request",
  "payments.refund_approve",
  "payments.void_request",
  "payments.void_approve",
  "packages.view",
  "packages.sell",
  "packages.use_session",
  "packages.adjust_session",
  "inventory.view",
  "inventory.receive",
  "inventory.consume",
  "inventory.adjust",
  "inventory.transfer",
  "reports.view_branch",
  "reports.view_all",
  "reports.export",
  "employees.view",
  "employees.create",
  "employees.update",
  "employees.disable",
  "security.view_audit",
  "security.manage_roles",
  "security.manage_devices",
  "security.break_glass",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_KEYS = [
  "owner",
  "super_admin",
  "branch_manager",
  "receptionist",
  "cashier",
  "aesthetician",
  "nurse",
  "doctor",
  "inventory_officer",
  "marketing",
  "auditor",
  "patient",
] as const;

export type RoleKey = (typeof ROLE_KEYS)[number];

const allPermissions = new Set<Permission>(PERMISSIONS);

export const rolePermissions: Record<RoleKey, Permission[]> = {
  owner: [...PERMISSIONS],
  super_admin: [...PERMISSIONS],
  branch_manager: [
    "dashboard.branch.view",
    "patients.view_basic",
    "patients.create",
    "patients.update_basic",
    "patients.archive",
    "patients.reveal_contact",
    "medical.view_summary",
    "appointments.view",
    "appointments.create",
    "appointments.confirm",
    "appointments.reschedule",
    "appointments.cancel",
    "services.view",
    "prices.view",
    "prices.propose",
    "prices.approve",
    "payments.view",
    "packages.view",
    "inventory.view",
    "reports.view_branch",
    "employees.view",
    "security.view_audit",
    "security.manage_devices",
  ],
  receptionist: [
    "dashboard.branch.view",
    "patients.view_basic",
    "patients.create",
    "patients.update_basic",
    "patients.reveal_contact",
    "appointments.view",
    "appointments.create",
    "appointments.confirm",
    "appointments.reschedule",
    "appointments.cancel",
    "appointments.check_in",
    "packages.view",
  ],
  cashier: [
    "dashboard.branch.view",
    "patients.view_basic",
    "appointments.view",
    "payments.create",
    "payments.view",
    "payments.refund_request",
    "payments.void_request",
    "packages.view",
    "packages.sell",
    "reports.view_branch",
  ],
  aesthetician: [
    "dashboard.branch.view",
    "patients.view_basic",
    "medical.view_summary",
    "medical.create",
    "medical.update",
    "clinical_photos.view",
    "clinical_photos.upload",
    "appointments.view",
    "appointments.start_treatment",
    "appointments.complete",
    "packages.view",
    "packages.use_session",
  ],
  nurse: [
    "dashboard.branch.view",
    "patients.view_basic",
    "patients.reveal_contact",
    "medical.view_summary",
    "medical.create",
    "medical.update",
    "clinical_photos.view",
    "clinical_photos.upload",
    "appointments.view",
    "appointments.create",
    "appointments.start_treatment",
    "appointments.complete",
    "packages.use_session",
    "inventory.consume",
  ],
  doctor: [
    "dashboard.branch.view",
    "patients.view_basic",
    "patients.reveal_contact",
    "medical.view_summary",
    "medical.view_full",
    "medical.create",
    "medical.update",
    "medical.sign",
    "medical.add_addendum",
    "clinical_photos.view",
    "clinical_photos.upload",
    "clinical_photos.download",
    "clinical_photos.view_sensitive",
    "appointments.view",
    "appointments.create",
    "appointments.start_treatment",
    "appointments.complete",
    "packages.use_session",
  ],
  inventory_officer: [
    "dashboard.branch.view",
    "inventory.view",
    "inventory.receive",
    "inventory.consume",
    "inventory.adjust",
    "inventory.transfer",
    "reports.view_branch",
  ],
  marketing: [
    "dashboard.branch.view",
    "patients.view_basic",
    "services.view",
    "packages.view",
    "reports.view_branch",
  ],
  auditor: [
    "dashboard.branch.view",
    "patients.view_basic",
    "medical.view_summary",
    "payments.view",
    "reports.view_branch",
    "reports.view_all",
    "reports.export",
    "security.view_audit",
  ],
  patient: ["patients.view_basic", "appointments.create", "packages.view"],
};

for (const [role, permissions] of Object.entries(rolePermissions)) {
  for (const permission of permissions) {
    if (!allPermissions.has(permission)) {
      throw new Error(`Unknown permission ${permission} for role ${role}`);
    }
  }
}
