import type { PublicReview } from "./types";

// Transcribed from the owner-supplied Facebook Reviews screenshots dated 2026-08-09.
// Facebook recommendations do not display star ratings, so rating remains null.
export const ownerSuppliedReviews: ReadonlyArray<PublicReview> = [
  {
    id: "facebook-ley-carrido-2024-10-14",
    reviewerDisplayName: "Ley Carrido",
    reviewText:
      "Thank you so much Esclare 🥰 very accommodating ang mga staff nyo inasikaso agad nila ako also super nagustuhan ko ang facial 👌 pang 4th visit ko na din to sainyo kasi nung 1st-3rd visit ko IPL underarm laser inaavail ko sainyo. Sana maka visit ako ulit sainyo soon ✨",
    rating: null,
    reviewDate: "2024-10-14",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: true,
    clinicResponse: null,
  },
  {
    id: "facebook-idyll-ruth-basino-zaens-2024-10-14",
    reviewerDisplayName: "Idyll Ruth Basiño-Zaens",
    reviewText:
      "The facial was incredibly relaxing; I even fell asleep during the mask application. The staff was very accommodating, they allowed me to start the treatment despite arriving 20 min ahead of schedule. Highly recommended for anyone looking for a painless and enjoyable facial experience. You're in great hands here.",
    rating: null,
    reviewDate: "2024-10-14",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: true,
    clinicResponse: null,
  },
  {
    id: "facebook-raven-rubio-2024-10-11",
    reviewerDisplayName: "Raven Rubio",
    reviewText:
      "Super satisfied ako sa facial treatment na ginawa sakin. Buti nalang napili ako for free facial treatment its my first time. Will definitely come back, plus mababait ang staff/s. Thank you Esclare Aesthetic & Laser Center 🥰",
    rating: null,
    reviewDate: "2024-10-11",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-jommel-a-chanco-2024-10-11",
    reviewerDisplayName: "Jommel A. Chanco",
    reviewText:
      "Thank you so much Esclare Aesthetic and Laser Center for taking care of my face. All the staff are very nice. I feel young again. Thank you sa nag facial sa akin talagang maingat sya sa pag handle ng face ko. Maraming salamat po ulet. ❤️❤️❤️",
    rating: null,
    reviewDate: "2024-10-11",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: true,
    clinicResponse: null,
  },
  {
    id: "facebook-menica-bandola-2024-10-10",
    reviewerDisplayName: "Menica Bandola",
    reviewText:
      "First time sakin to and thank you Esclare Aesthetic & Laser Center kasi napaka asikaso nang mga staff and very nice. Subra saram sa face at nakaka relax.",
    rating: null,
    reviewDate: "2024-10-10",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-gubat-shahani-2024-10-10",
    reviewerDisplayName: "Gubat Shahani",
    reviewText:
      "This is my 4x here and I was completely impressed with their professionalism and customer service. Very accommodating staffs. The ambiance here is always inviting and comfortable. And I want to say THANK You for being one of the lucky winners of FREE FACIAL. 🙏",
    rating: null,
    reviewDate: "2024-10-10",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: true,
    clinicResponse: null,
  },
  {
    id: "facebook-julianna-villamil-2024-10-10",
    reviewerDisplayName: "Julianna Villamil",
    reviewText:
      "It's my 2nd time here and still gentle pa din ang staff sa pag pafacial and still ang gaan sa pakiramdam after. Thank you so much po!",
    rating: null,
    reviewDate: "2024-10-10",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-bham-felices-pares-2024-10-09",
    reviewerDisplayName: "Bham Felices Pares",
    reviewText:
      "Thank you so much, esclare is highly recommended for those who want to be more beautiful, especially momsh, it's very relaxing, it removes stress 😍😍 ang babait pa nang mga staff 😊",
    rating: null,
    reviewDate: "2024-10-09",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-ruth-joy-referiza-vibares-2024-10-09",
    reviewerDisplayName: "Ruth Joy Referiza-Vibares",
    reviewText: "Thank u so much Esclare! Nice place, staff and service ❤️",
    rating: null,
    reviewDate: "2024-10-09",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: true,
    clinicResponse: null,
  },
  {
    id: "facebook-rose-naya-2024-10-08",
    reviewerDisplayName: "Rose Naya",
    reviewText:
      "Very nice po ang mga Aestheticians and accommodating 😊 Marerelax ka talaga and very comfortable pa ang place 💕 First time ko pero sobrang gagaling nila mag handle ng skin very gentle and with care 💖 Thankyou so much po",
    rating: null,
    reviewDate: "2024-10-08",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: true,
    clinicResponse: null,
  },
  {
    id: "facebook-modelo-bikolano-2024-02-06",
    reviewerDisplayName: "Modelo Bikolano by Anjo Santos",
    reviewText:
      "Top notched Aesthetic Center not only in the metro of Naga but all throughout Bicolandia. Will not settle your satisfaction with an average result but will give you more than what the client deserved. Very Accommodating & warm prople also very polite, gentle and exceedingly professionals worth to entrust about your look. 🥰",
    rating: null,
    reviewDate: "2024-02-06",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-edna-iglas-bea-2020-07-06",
    reviewerDisplayName: "Edna Iglas Bea",
    reviewText:
      "Ganda ng result nung Diode Laser Hair Removal kahit na isang beses palang akong nagtry. Very accommodating din yung staff nila. Thank you Esclare. 🥰",
    rating: null,
    reviewDate: "2020-07-06",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse:
      "Thank you Ms. Edna we're pleased you liked the results. We would love to see you again. Keep safe ❤️",
  },
  {
    id: "facebook-aileen-aquitan-pestolante-2020-05-19",
    reviewerDisplayName: "Aileen Aquitan Pestolante",
    reviewText: "they are professional.its nice",
    rating: null,
    reviewDate: "2020-05-19",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-letty-basto-2019-04-25",
    reviewerDisplayName: "Letty Basto",
    reviewText: "Happy with the service,they knows what'sbest thank you esclare\n\nExpert facials",
    rating: null,
    reviewDate: "2019-04-25",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-jing-relata-brioso-2018-07-18",
    reviewerDisplayName: "Jing Relata Brioso",
    reviewText:
      "Thank you so much for the free facial! Even though it's free, malinis and di minadali ang pag facial. I will surely come back.",
    rating: null,
    reviewDate: "2018-07-18",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
  {
    id: "facebook-shojimar-yoshida-2018-05-27",
    reviewerDisplayName: "Shojimar Yoshida",
    reviewText: "thumbs up!",
    rating: null,
    reviewDate: "2018-05-27",
    source: "facebook",
    originalReviewUrl: null,
    sourceProfileUrl: null,
    verified: true,
    featured: false,
    clinicResponse: null,
  },
] as const;
