import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MapPin, ShieldCheck, Stethoscope } from "lucide-react";
import { AttendantSection } from "@/components/public/attendant-section";
import { AuthenticHero } from "@/components/public/authentic-hero";
import { ClinicGallery } from "@/components/public/clinic-gallery";
import { PremiumCounters } from "@/components/public/premium-counters";
import { diodeMachine } from "@/lib/clinic/media";
import { treatments } from "@/lib/services/catalog";

export const metadata: Metadata = { title: "Aesthetic & Wellness Clinic in Naga and Daet", description: "Discover thoughtful aesthetic and wellness care at ESCLARE Naga and Daet. Explore regular prices and request an appointment with no booking deposit.", alternates: { canonical: "/home" } };
const featured = ["korean-facial", "pico-glow-face", "7d-hifu-face", "mccm-pdrn"];

export default function PublicHomePage() {
  const featuredTreatments = featured.map((slug) => treatments.find((item) => item.slug === slug)!);
  return <main><AuthenticHero />
    <section className="bg-white py-10 sm:py-14"><div className="public-container"><PremiumCounters /></div></section>

    <section className="py-20 lg:py-28"><div className="public-container grid gap-12 lg:grid-cols-[0.42fr_0.58fr] lg:gap-20"><div data-reveal><p className="public-eyebrow">The ESCLARE experience</p><h2 className="public-subheading mt-4">Premium care should feel clear, personal, and reassuring.</h2></div><div data-reveal="right"><p className="leading-8 text-[#62595C]">From consultation to aftercare, every visit is guided by your goals, treatment suitability, and a plan you can understand. Doctor-required services are clearly identified and scheduled around clinical availability.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="flex gap-3"><ShieldCheck className="mt-1 shrink-0 text-[#9A7740]" size={21} /><div><h3 className="font-sans text-sm font-bold text-[#3A2029]">Assessment-led</h3><p className="mt-1 text-sm leading-6 text-[#6B6264]">Suitability comes before recommendations.</p></div></div><div className="flex gap-3"><CheckCircle2 className="mt-1 shrink-0 text-[#9A7740]" size={21} /><div><h3 className="font-sans text-sm font-bold text-[#3A2029]">Clear pricing</h3><p className="mt-1 text-sm leading-6 text-[#6B6264]">Published regular rates, without expired promos.</p></div></div></div><Link href="/about" className="luxury-button-outline mt-9">Discover our approach <ArrowRight size={16} /></Link></div></div></section>

    <section className="bg-[#EEE6DA] py-20 lg:py-28"><div className="public-container"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between" data-reveal><div><p className="public-eyebrow">Signature care</p><h2 className="public-subheading mt-4">Treatments selected around you.</h2></div><Link href="/treatments" className="public-link w-fit py-3 text-sm font-bold text-[#5B1830]">View all treatments <ArrowRight className="ml-1 inline" size={16} /></Link></div><div className="mt-10 grid gap-px bg-[#CCBCA7] sm:grid-cols-2 lg:grid-cols-4">{featuredTreatments.map((item, index) => <Link href={`/treatments#${item.category.replaceAll(" ", "-").toLowerCase()}`} key={item.slug} data-reveal className="group min-h-60 bg-[#FBF8F2] p-6 transition-colors hover:bg-white"><span className="font-serif text-sm text-[#A17E48]">0{index + 1}</span><div className="mt-12"><h3 className="text-2xl text-[#481827] transition-transform duration-300 group-hover:-translate-y-1">{item.name}</h3><p className="mt-3 text-sm leading-6 text-[#686063]">{item.summary}</p><ArrowRight className="mt-6 text-[#6F263D] transition-transform group-hover:translate-x-2" size={18} /></div></Link>)}</div></div></section>

    <section className="overflow-hidden bg-[#32101E] py-20 text-white lg:py-28"><div className="public-container grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div className="relative mx-auto aspect-[9/11] w-full max-w-lg bg-[#FBF8F2]" data-reveal="left"><Image src={diodeMachine.src} alt={diodeMachine.alt} width={diodeMachine.width} height={diodeMachine.height} sizes="(min-width: 1024px) 40vw, 90vw" className="size-full object-contain p-6 sm:p-10" /><div className="absolute bottom-0 left-0 bg-[#5B1830] px-5 py-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#E8D5B5]">Actual ESCLARE equipment</p></div></div><div data-reveal="right"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#D4B77D]">4-wavelength diode</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Technology you can see. Guidance you can trust.</h2><p className="mt-6 leading-8 text-[#E7DAD2]">ESCLARE uses a four-wavelength diode laser system designed to address hair at different follicle depths. Cooling support helps make sessions more comfortable, while treatment intervals and the recommended course remain individualized.</p><div className="mt-8 grid gap-4 text-sm text-[#F2E7E0] sm:grid-cols-2"><p className="border-l border-[#C4A064] pl-4">Multiple wavelengths for broader treatment coverage</p><p className="border-l border-[#C4A064] pl-4">Cooling-supported treatment experience</p><p className="border-l border-[#C4A064] pl-4">Monthly intervals commonly recommended</p><p className="border-l border-[#C4A064] pl-4">Results vary by hair, hormones, area, and consistency</p></div><Link href="/diode-laser" className="luxury-button-light mt-9">Explore 4D Diode <ArrowRight size={16} /></Link></div></div></section>

    <ClinicGallery compact />
    <AttendantSection />

    <section className="py-20 lg:py-28"><div className="public-container"><div data-reveal><p className="public-eyebrow">Your treatment journey</p><h2 className="public-subheading mt-4 max-w-3xl">Simple steps, clear expectations.</h2></div><div className="mt-10 grid gap-px bg-[#D8C9B4] md:grid-cols-3">{[["01","Request","Choose your branch, treatment, preferred date, and preferred time."],["02","Confirm","The team checks staff, doctor, room, and equipment availability."],["03","Visit","Arrive for assessment and a treatment plan suited to your goals."]].map(([number,title,copy]) => <article key={number} className="bg-white p-7" data-reveal><p className="font-serif text-3xl text-[#A17E48]">{number}</p><h3 className="mt-10 text-2xl text-[#481827]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#62595C]">{copy}</p></article>)}</div></div></section>

    <section className="bg-[#5B1830] py-16 text-white"><div className="public-container grid gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div data-reveal><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#E8D5B5]">Visit with confidence</p><h2 className="mt-4 max-w-3xl font-serif text-3xl leading-tight sm:text-5xl">Two welcoming branches, one considered standard of care.</h2><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[#F0DFD3]"><span className="inline-flex items-center gap-2"><MapPin size={16} /> Naga City</span><span className="inline-flex items-center gap-2"><MapPin size={16} /> Daet</span><span className="inline-flex items-center gap-2"><Stethoscope size={16} /> Saturday doctor schedule</span></div></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link href="/branches" className="luxury-button-light">Find a branch</Link><Link href="/appointment-request" className="luxury-button-ghost">Book a visit</Link></div></div></section>
  </main>;
}
